/**
 * @brief AUTO GENERATED BY `genwrap.pl'! DO NOT EDIT!
 *  This is wrapper for libexjava.so so that we expose loaded symbols
 *  globally. Otherwise XA drivers from SO cannot access the enduro/x symbols.
 *
 * @file loader.c
 */
/* -----------------------------------------------------------------------------
 * Enduro/X Middleware Platform for Distributed Transaction Processing
 * Copyright (C) 2009-2016, ATR Baltic, Ltd. All Rights Reserved.
 * Copyright (C) 2017-2018, Mavimax, Ltd. All Rights Reserved.
 * This software is released under one of the following licenses:
 * AGPL or Mavimax's license for commercial use.
 * -----------------------------------------------------------------------------
 * AGPL license:
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License, version 3 as published
 * by the Free Software Foundation;
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE. See the GNU Affero General Public License, version 3
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along 
 * with this program; if not, write to the Free Software Foundation, Inc., 
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *
 * -----------------------------------------------------------------------------
 * A commercial use license is available from Mavimax, Ltd
 * contact@mavimax.com
 * -----------------------------------------------------------------------------
 */
#include <string.h>
#include <stdio.h>
#include <stdlib.h>

#include <ndrstandard.h>
#include <ndebug.h>
#include <atmi.h>
#include <sys_mqueue.h>
#include <thlock.h>

#include <tmenv.h>
#include <libsrc.h>

#include <xa.h>
#define __USE_GNU
#include <dlfcn.h>
/* List of pointers to loaded library functions: */
#include <org_endurox_AtmiCtx.h>
#include <org_endurox_BExprTree.h>
#include <org_endurox_TypedBuffer.h>
#include <org_endurox_TypedCarray.h>
#include <org_endurox_TypedJson.h>
#include <org_endurox_TypedString.h>
#include <org_endurox_TypedUbf.h>
/*---------------------------Externs------------------------------------*/
/*---------------------------Macros-------------------------------------*/
/*---------------------------Enums--------------------------------------*/
/*---------------------------Typedefs-----------------------------------*/

/**
 * Symbol mapping table
 */
struct ndrxj_loader_map
{
    char    *symbol;        /**< Symbol name                                  */
    void    **funcptr;      /**< Pointer to function                          */
};
typedef struct ndrxj_loader_map ndrxj_loader_map_t;


/*---------------------------Globals------------------------------------*/
/*---------------------------Statics------------------------------------*/

/* List of pointers to loaded library functions: */
exprivate jobject (*p_ndrxj_Java_org_endurox_AtmiCtx_getAtmiError)
        (JNIEnv * v0,  jobject v1) = NULL;
exprivate jlong (*p_ndrxj_Java_org_endurox_AtmiCtx_tpnewctxt)
        (JNIEnv * v0,  jclass v1) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_AtmiCtx_tpfreectxt)
        (JNIEnv * v0,  jclass v1,  jlong v2) = NULL;
exprivate jobject (*p_ndrxj_Java_org_endurox_AtmiCtx_tpalloc)
        (JNIEnv * v0,  jobject v1,  jstring v2,  jstring v3,  jlong v4) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_AtmiCtx_tpterm)
        (JNIEnv * v0,  jobject v1) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_AtmiCtx_finalizeC)
        (JNIEnv * v0,  jclass v1,  jlong v2) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_AtmiCtx_tpreturn)
        (JNIEnv * v0,  jobject v1,  jint v2,  jlong v3,  jobject v4,  jlong v5) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_AtmiCtx_tpforward)
        (JNIEnv * v0,  jobject v1,  jstring v2,  jobject v3,  jlong v4) = NULL;
exprivate jint (*p_ndrxj_Java_org_endurox_AtmiCtx_tpRunC)
        (JNIEnv * v0,  jobject v1,  jobjectArray v2,  jboolean v3) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_AtmiCtx_tplogC)
        (JNIEnv * v0,  jobject v1,  jint v2,  jstring v3,  jlong v4,  jstring v5) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_AtmiCtx_tplogndrxC)
        (JNIEnv * v0,  jobject v1,  jint v2,  jstring v3,  jlong v4,  jstring v5) = NULL;
exprivate jint (*p_ndrxj_Java_org_endurox_AtmiCtx_tplogqinfo)
        (JNIEnv * v0,  jobject v1,  jint v2,  jlong v3) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_AtmiCtx_tpadvertiseC)
        (JNIEnv * v0,  jobject v1,  jstring v2,  jstring v3) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_AtmiCtx_tplogubfex)
        (JNIEnv * v0,  jobject v1,  jint v2,  jstring v3,  jthrowable v4) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_AtmiCtx_tplogndrxex)
        (JNIEnv * v0,  jobject v1,  jint v2,  jstring v3,  jthrowable v4) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_AtmiCtx_tplogex)
        (JNIEnv * v0,  jobject v1,  jint v2,  jstring v3,  jthrowable v4) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_AtmiCtx_userlogex)
        (JNIEnv * v0,  jobject v1,  jstring v2,  jthrowable v3) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_AtmiCtx_tplogDump)
        (JNIEnv * v0,  jobject v1,  jint v2,  jstring v3,  jbyteArray v4) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_AtmiCtx_tplogDumpDiff)
        (JNIEnv * v0,  jobject v1,  jint v2,  jstring v3,  jbyteArray v4,  jbyteArray v5) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_AtmiCtx_tpinit)
        (JNIEnv * v0,  jobject v1,  jobject v2) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_AtmiCtx_userlogC)
        (JNIEnv * v0,  jobject v1,  jstring v2) = NULL;
exprivate jobject (*p_ndrxj_Java_org_endurox_AtmiCtx_tpcall)
        (JNIEnv * v0,  jobject v1,  jstring v2,  jobject v3,  jlong v4) = NULL;
exprivate jint (*p_ndrxj_Java_org_endurox_AtmiCtx_tpacall)
        (JNIEnv * v0,  jobject v1,  jstring v2,  jobject v3,  jlong v4) = NULL;
exprivate jobject (*p_ndrxj_Java_org_endurox_AtmiCtx_tpgetrply)
        (JNIEnv * v0,  jobject v1,  jint v2,  jobject v3,  jlong v4) = NULL;
exprivate jint (*p_ndrxj_Java_org_endurox_AtmiCtx_tpconnect)
        (JNIEnv * v0,  jobject v1,  jstring v2,  jobject v3,  jlong v4) = NULL;
exprivate jlong (*p_ndrxj_Java_org_endurox_AtmiCtx_tpsend)
        (JNIEnv * v0,  jobject v1,  jint v2,  jobject v3,  jlong v4) = NULL;
exprivate jobject (*p_ndrxj_Java_org_endurox_AtmiCtx_tprecv)
        (JNIEnv * v0,  jobject v1,  jint v2,  jobject v3,  jlong v4) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_AtmiCtx_tpdiscon)
        (JNIEnv * v0,  jobject v1,  jint v2) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_AtmiCtx_tpcancel)
        (JNIEnv * v0,  jobject v1,  jint v2) = NULL;
exprivate jobject (*p_ndrxj_Java_org_endurox_AtmiCtx_Bboolco)
        (JNIEnv * v0,  jobject v1,  jstring v2) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_AtmiCtx_Bboolpr)
        (JNIEnv * v0,  jobject v1,  jobject v2,  jobject v3) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_AtmiCtx_BboolsetcbfC)
        (JNIEnv * v0,  jobject v1,  jstring v2) = NULL;
exprivate jstring (*p_ndrxj_Java_org_endurox_AtmiCtx_Btype)
        (JNIEnv * v0,  jobject v1,  jint v2) = NULL;
exprivate jstring (*p_ndrxj_Java_org_endurox_AtmiCtx_Bfname)
        (JNIEnv * v0,  jobject v1,  jint v2) = NULL;
exprivate jint (*p_ndrxj_Java_org_endurox_AtmiCtx_tptoutget)
        (JNIEnv * v0,  jobject v1) = NULL;
exprivate jlong (*p_ndrxj_Java_org_endurox_AtmiCtx_tpurcode)
        (JNIEnv * v0,  jobject v1) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_AtmiCtx_tptoutset)
        (JNIEnv * v0,  jobject v1,  jint v2) = NULL;
exprivate jlongArray (*p_ndrxj_Java_org_endurox_AtmiCtx_getBuffers)
        (JNIEnv * v0,  jobject v1) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_AtmiCtx_tpsetunsolC)
        (JNIEnv * v0,  jobject v1,  jobject v2) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_AtmiCtx_tpnotify)
        (JNIEnv * v0,  jobject v1,  jobject v2,  jobject v3,  jlong v4) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_AtmiCtx_tpbroadcast)
        (JNIEnv * v0,  jobject v1,  jstring v2,  jstring v3,  jstring v4,  jobject v5,  jlong v6) = NULL;
exprivate jint (*p_ndrxj_Java_org_endurox_AtmiCtx_tpchkunsol)
        (JNIEnv * v0,  jobject v1) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_AtmiCtx_tpenqueue)
        (JNIEnv * v0,  jobject v1,  jstring v2,  jstring v3,  jobject v4,  jobject v5,  jlong v6) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_AtmiCtx_tpenqueueex)
        (JNIEnv * v0,  jobject v1,  jshort v2,  jshort v3,  jstring v4,  jobject v5,  jobject v6,  jlong v7) = NULL;
exprivate jobject (*p_ndrxj_Java_org_endurox_AtmiCtx_tpdequeue)
        (JNIEnv * v0,  jobject v1,  jstring v2,  jstring v3,  jobject v4,  jobject v5,  jlong v6) = NULL;
exprivate jobject (*p_ndrxj_Java_org_endurox_AtmiCtx_tpdequeueex)
        (JNIEnv * v0,  jobject v1,  jshort v2,  jshort v3,  jstring v4,  jobject v5,  jobject v6,  jlong v7) = NULL;
exprivate jlong (*p_ndrxj_Java_org_endurox_AtmiCtx_tpsrvgetctxdata)
        (JNIEnv * v0,  jobject v1) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_AtmiCtx_tpsrvsetctxdata)
        (JNIEnv * v0,  jobject v1,  jlong v2,  jlong v3) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_AtmiCtx_tpsrvfreectxdata)
        (JNIEnv * v0,  jobject v1,  jlong v2) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_AtmiCtx_tpcontinue)
        (JNIEnv * v0,  jobject v1) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_AtmiCtx_tpopen)
        (JNIEnv * v0,  jobject v1) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_AtmiCtx_tpclose)
        (JNIEnv * v0,  jobject v1) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_AtmiCtx_tpbegin)
        (JNIEnv * v0,  jobject v1,  jlong v2,  jlong v3) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_AtmiCtx_tpcommit)
        (JNIEnv * v0,  jobject v1,  jlong v2) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_AtmiCtx_tpabort)
        (JNIEnv * v0,  jobject v1,  jlong v2) = NULL;
exprivate jobject (*p_ndrxj_Java_org_endurox_AtmiCtx_tpsuspend)
        (JNIEnv * v0,  jobject v1,  jlong v2) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_AtmiCtx_tpresume)
        (JNIEnv * v0,  jobject v1,  jobject v2,  jlong v3) = NULL;
exprivate jint (*p_ndrxj_Java_org_endurox_AtmiCtx_tpgetlev)
        (JNIEnv * v0,  jobject v1) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_AtmiCtx_installTermSigHandler)
        (JNIEnv * v0,  jobject v1,  jobject v2) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_BExprTree_Btreefree)
        (JNIEnv * v0,  jobject v1,  jlong v2) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedBuffer_tpfree)
        (JNIEnv * v0,  jobject v1,  jlong v2) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedBuffer_tprealloc)
        (JNIEnv * v0,  jobject v1,  jlong v2) = NULL;
exprivate jobject (*p_ndrxj_Java_org_endurox_TypedBuffer_tptypes)
        (JNIEnv * v0,  jobject v1) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedCarray_setBytes)
        (JNIEnv * v0,  jobject v1,  jbyteArray v2) = NULL;
exprivate jbyteArray (*p_ndrxj_Java_org_endurox_TypedCarray_getBytes)
        (JNIEnv * v0,  jobject v1) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedJson_setJSON)
        (JNIEnv * v0,  jobject v1,  jstring v2) = NULL;
exprivate jstring (*p_ndrxj_Java_org_endurox_TypedJson_getJSON)
        (JNIEnv * v0,  jobject v1) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedString_setString)
        (JNIEnv * v0,  jobject v1,  jstring v2) = NULL;
exprivate jstring (*p_ndrxj_Java_org_endurox_TypedString_getString)
        (JNIEnv * v0,  jobject v1) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedUbf_Badd__IS)
        (JNIEnv * v0,  jobject v1,  jint v2,  jshort v3) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedUbf_Badd__IJ)
        (JNIEnv * v0,  jobject v1,  jint v2,  jlong v3) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedUbf_Badd__IB)
        (JNIEnv * v0,  jobject v1,  jint v2,  jbyte v3) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedUbf_Badd__IF)
        (JNIEnv * v0,  jobject v1,  jint v2,  jfloat v3) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedUbf_Badd__ID)
        (JNIEnv * v0,  jobject v1,  jint v2,  jdouble v3) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedUbf_Badd__ILjava_lang_String_2)
        (JNIEnv * v0,  jobject v1,  jint v2,  jstring v3) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedUbf_Badd__I_3B)
        (JNIEnv * v0,  jobject v1,  jint v2,  jbyteArray v3) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedUbf_Bprint)
        (JNIEnv * v0,  jobject v1) = NULL;
exprivate jshort (*p_ndrxj_Java_org_endurox_TypedUbf_BgetShort)
        (JNIEnv * v0,  jobject v1,  jint v2,  jint v3) = NULL;
exprivate jlong (*p_ndrxj_Java_org_endurox_TypedUbf_BgetLong)
        (JNIEnv * v0,  jobject v1,  jint v2,  jint v3) = NULL;
exprivate jbyte (*p_ndrxj_Java_org_endurox_TypedUbf_BgetByte)
        (JNIEnv * v0,  jobject v1,  jint v2,  jint v3) = NULL;
exprivate jfloat (*p_ndrxj_Java_org_endurox_TypedUbf_BgetFloat)
        (JNIEnv * v0,  jobject v1,  jint v2,  jint v3) = NULL;
exprivate jdouble (*p_ndrxj_Java_org_endurox_TypedUbf_BgetDouble)
        (JNIEnv * v0,  jobject v1,  jint v2,  jint v3) = NULL;
exprivate jstring (*p_ndrxj_Java_org_endurox_TypedUbf_BgetString)
        (JNIEnv * v0,  jobject v1,  jint v2,  jint v3) = NULL;
exprivate jbyteArray (*p_ndrxj_Java_org_endurox_TypedUbf_BgetByteArr)
        (JNIEnv * v0,  jobject v1,  jint v2,  jint v3) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedUbf_Baddfast__ISLorg_endurox_BFldLocInfo_2)
        (JNIEnv * v0,  jobject v1,  jint v2,  jshort v3,  jobject v4) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedUbf_Baddfast__IJLorg_endurox_BFldLocInfo_2)
        (JNIEnv * v0,  jobject v1,  jint v2,  jlong v3,  jobject v4) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedUbf_Baddfast__IBLorg_endurox_BFldLocInfo_2)
        (JNIEnv * v0,  jobject v1,  jint v2,  jbyte v3,  jobject v4) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedUbf_Baddfast__IFLorg_endurox_BFldLocInfo_2)
        (JNIEnv * v0,  jobject v1,  jint v2,  jfloat v3,  jobject v4) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedUbf_Baddfast__IDLorg_endurox_BFldLocInfo_2)
        (JNIEnv * v0,  jobject v1,  jint v2,  jdouble v3,  jobject v4) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedUbf_Baddfast__ILjava_lang_String_2Lorg_endurox_BFldLocInfo_2)
        (JNIEnv * v0,  jobject v1,  jint v2,  jstring v3,  jobject v4) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedUbf_Baddfast__I_3BLorg_endurox_BFldLocInfo_2)
        (JNIEnv * v0,  jobject v1,  jint v2,  jbyteArray v3,  jobject v4) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedUbf_Bchg__IIS)
        (JNIEnv * v0,  jobject v1,  jint v2,  jint v3,  jshort v4) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedUbf_Bchg__IIJ)
        (JNIEnv * v0,  jobject v1,  jint v2,  jint v3,  jlong v4) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedUbf_Bchg__IIB)
        (JNIEnv * v0,  jobject v1,  jint v2,  jint v3,  jbyte v4) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedUbf_Bchg__IIF)
        (JNIEnv * v0,  jobject v1,  jint v2,  jint v3,  jfloat v4) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedUbf_Bchg__IID)
        (JNIEnv * v0,  jobject v1,  jint v2,  jint v3,  jdouble v4) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedUbf_Bchg__IILjava_lang_String_2)
        (JNIEnv * v0,  jobject v1,  jint v2,  jint v3,  jstring v4) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedUbf_Bchg__II_3B)
        (JNIEnv * v0,  jobject v1,  jint v2,  jint v3,  jbyteArray v4) = NULL;
exprivate jboolean (*p_ndrxj_Java_org_endurox_TypedUbf_Bboolev)
        (JNIEnv * v0,  jobject v1,  jobject v2) = NULL;
exprivate jboolean (*p_ndrxj_Java_org_endurox_TypedUbf_Bqboolev)
        (JNIEnv * v0,  jobject v1,  jstring v2) = NULL;
exprivate jdouble (*p_ndrxj_Java_org_endurox_TypedUbf_Bfloatev)
        (JNIEnv * v0,  jobject v1,  jobject v2) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedUbf_Bdel)
        (JNIEnv * v0,  jobject v1,  jint v2,  jint v3) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedUbf_Bdelall)
        (JNIEnv * v0,  jobject v1,  jint v2) = NULL;
exprivate jboolean (*p_ndrxj_Java_org_endurox_TypedUbf_Bpres)
        (JNIEnv * v0,  jobject v1,  jint v2,  jint v3) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedUbf_Bextread)
        (JNIEnv * v0,  jobject v1,  jobject v2) = NULL;
exprivate jboolean (*p_ndrxj_Java_org_endurox_TypedUbf_Bisubf)
        (JNIEnv * v0,  jobject v1) = NULL;
exprivate jint (*p_ndrxj_Java_org_endurox_TypedUbf_Blen)
        (JNIEnv * v0,  jobject v1,  jint v2,  jint v3) = NULL;
exprivate jobject (*p_ndrxj_Java_org_endurox_TypedUbf_Bnext)
        (JNIEnv * v0,  jobject v1,  jboolean v2) = NULL;
exprivate jint (*p_ndrxj_Java_org_endurox_TypedUbf_Boccur)
        (JNIEnv * v0,  jobject v1,  jint v2) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedUbf_Bproj)
        (JNIEnv * v0,  jobject v1,  jintArray v2) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedUbf_Bread)
        (JNIEnv * v0,  jobject v1,  jbyteArray v2) = NULL;
exprivate jbyteArray (*p_ndrxj_Java_org_endurox_TypedUbf_Bwrite)
        (JNIEnv * v0,  jobject v1) = NULL;
exprivate jlong (*p_ndrxj_Java_org_endurox_TypedUbf_Bsizeof)
        (JNIEnv * v0,  jobject v1) = NULL;
exprivate jlong (*p_ndrxj_Java_org_endurox_TypedUbf_Bunused)
        (JNIEnv * v0,  jobject v1) = NULL;
exprivate jlong (*p_ndrxj_Java_org_endurox_TypedUbf_Bused)
        (JNIEnv * v0,  jobject v1) = NULL;
exprivate jlong (*p_ndrxj_Java_org_endurox_TypedUbf_Binit)
        (JNIEnv * v0,  jobject v1) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedUbf_Bdelete)
        (JNIEnv * v0,  jobject v1,  jintArray v2) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedUbf_Bconcat)
        (JNIEnv * v0,  jobject v1,  jobject v2) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedUbf_Bcpy)
        (JNIEnv * v0,  jobject v1,  jobject v2) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedUbf_Bprojcpy)
        (JNIEnv * v0,  jobject v1,  jobject v2,  jintArray v3) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedUbf_Bupdate)
        (JNIEnv * v0,  jobject v1,  jobject v2) = NULL;
exprivate jint (*p_ndrxj_Java_org_endurox_TypedUbf_Bcmp)
        (JNIEnv * v0,  jobject v1,  jobject v2) = NULL;
exprivate jboolean (*p_ndrxj_Java_org_endurox_TypedUbf_Bsubset)
        (JNIEnv * v0,  jobject v1,  jobject v2) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedUbf_tpjsontoubf)
        (JNIEnv * v0,  jobject v1,  jstring v2) = NULL;
exprivate jstring (*p_ndrxj_Java_org_endurox_TypedUbf_tpubftojson)
        (JNIEnv * v0,  jobject v1) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedUbf_tplogprintubf)
        (JNIEnv * v0,  jobject v1,  jint v2,  jstring v3) = NULL;
exprivate jint (*p_ndrxj_Java_org_endurox_TypedUbf_Bnum)
        (JNIEnv * v0,  jobject v1) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedUbf_Bjoin)
        (JNIEnv * v0,  jobject v1,  jobject v2) = NULL;
exprivate void (*p_ndrxj_Java_org_endurox_TypedUbf_Bojoin)
        (JNIEnv * v0,  jobject v1,  jobject v2) = NULL;
/**
 * Function mapping table
 */
exprivate ndrxj_loader_map_t M_funcmap[] =
{  
    /* generated list of maps: */
    {"ndrxj_Java_org_endurox_AtmiCtx_getAtmiError", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_getAtmiError},
    {"ndrxj_Java_org_endurox_AtmiCtx_tpnewctxt", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tpnewctxt},
    {"ndrxj_Java_org_endurox_AtmiCtx_tpfreectxt", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tpfreectxt},
    {"ndrxj_Java_org_endurox_AtmiCtx_tpalloc", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tpalloc},
    {"ndrxj_Java_org_endurox_AtmiCtx_tpterm", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tpterm},
    {"ndrxj_Java_org_endurox_AtmiCtx_finalizeC", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_finalizeC},
    {"ndrxj_Java_org_endurox_AtmiCtx_tpreturn", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tpreturn},
    {"ndrxj_Java_org_endurox_AtmiCtx_tpforward", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tpforward},
    {"ndrxj_Java_org_endurox_AtmiCtx_tpRunC", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tpRunC},
    {"ndrxj_Java_org_endurox_AtmiCtx_tplogC", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tplogC},
    {"ndrxj_Java_org_endurox_AtmiCtx_tplogndrxC", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tplogndrxC},
    {"ndrxj_Java_org_endurox_AtmiCtx_tplogqinfo", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tplogqinfo},
    {"ndrxj_Java_org_endurox_AtmiCtx_tpadvertiseC", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tpadvertiseC},
    {"ndrxj_Java_org_endurox_AtmiCtx_tplogubfex", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tplogubfex},
    {"ndrxj_Java_org_endurox_AtmiCtx_tplogndrxex", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tplogndrxex},
    {"ndrxj_Java_org_endurox_AtmiCtx_tplogex", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tplogex},
    {"ndrxj_Java_org_endurox_AtmiCtx_userlogex", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_userlogex},
    {"ndrxj_Java_org_endurox_AtmiCtx_tplogDump", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tplogDump},
    {"ndrxj_Java_org_endurox_AtmiCtx_tplogDumpDiff", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tplogDumpDiff},
    {"ndrxj_Java_org_endurox_AtmiCtx_tpinit", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tpinit},
    {"ndrxj_Java_org_endurox_AtmiCtx_userlogC", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_userlogC},
    {"ndrxj_Java_org_endurox_AtmiCtx_tpcall", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tpcall},
    {"ndrxj_Java_org_endurox_AtmiCtx_tpacall", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tpacall},
    {"ndrxj_Java_org_endurox_AtmiCtx_tpgetrply", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tpgetrply},
    {"ndrxj_Java_org_endurox_AtmiCtx_tpconnect", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tpconnect},
    {"ndrxj_Java_org_endurox_AtmiCtx_tpsend", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tpsend},
    {"ndrxj_Java_org_endurox_AtmiCtx_tprecv", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tprecv},
    {"ndrxj_Java_org_endurox_AtmiCtx_tpdiscon", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tpdiscon},
    {"ndrxj_Java_org_endurox_AtmiCtx_tpcancel", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tpcancel},
    {"ndrxj_Java_org_endurox_AtmiCtx_Bboolco", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_Bboolco},
    {"ndrxj_Java_org_endurox_AtmiCtx_Bboolpr", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_Bboolpr},
    {"ndrxj_Java_org_endurox_AtmiCtx_BboolsetcbfC", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_BboolsetcbfC},
    {"ndrxj_Java_org_endurox_AtmiCtx_Btype", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_Btype},
    {"ndrxj_Java_org_endurox_AtmiCtx_Bfname", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_Bfname},
    {"ndrxj_Java_org_endurox_AtmiCtx_tptoutget", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tptoutget},
    {"ndrxj_Java_org_endurox_AtmiCtx_tpurcode", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tpurcode},
    {"ndrxj_Java_org_endurox_AtmiCtx_tptoutset", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tptoutset},
    {"ndrxj_Java_org_endurox_AtmiCtx_getBuffers", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_getBuffers},
    {"ndrxj_Java_org_endurox_AtmiCtx_tpsetunsolC", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tpsetunsolC},
    {"ndrxj_Java_org_endurox_AtmiCtx_tpnotify", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tpnotify},
    {"ndrxj_Java_org_endurox_AtmiCtx_tpbroadcast", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tpbroadcast},
    {"ndrxj_Java_org_endurox_AtmiCtx_tpchkunsol", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tpchkunsol},
    {"ndrxj_Java_org_endurox_AtmiCtx_tpenqueue", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tpenqueue},
    {"ndrxj_Java_org_endurox_AtmiCtx_tpenqueueex", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tpenqueueex},
    {"ndrxj_Java_org_endurox_AtmiCtx_tpdequeue", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tpdequeue},
    {"ndrxj_Java_org_endurox_AtmiCtx_tpdequeueex", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tpdequeueex},
    {"ndrxj_Java_org_endurox_AtmiCtx_tpsrvgetctxdata", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tpsrvgetctxdata},
    {"ndrxj_Java_org_endurox_AtmiCtx_tpsrvsetctxdata", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tpsrvsetctxdata},
    {"ndrxj_Java_org_endurox_AtmiCtx_tpsrvfreectxdata", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tpsrvfreectxdata},
    {"ndrxj_Java_org_endurox_AtmiCtx_tpcontinue", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tpcontinue},
    {"ndrxj_Java_org_endurox_AtmiCtx_tpopen", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tpopen},
    {"ndrxj_Java_org_endurox_AtmiCtx_tpclose", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tpclose},
    {"ndrxj_Java_org_endurox_AtmiCtx_tpbegin", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tpbegin},
    {"ndrxj_Java_org_endurox_AtmiCtx_tpcommit", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tpcommit},
    {"ndrxj_Java_org_endurox_AtmiCtx_tpabort", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tpabort},
    {"ndrxj_Java_org_endurox_AtmiCtx_tpsuspend", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tpsuspend},
    {"ndrxj_Java_org_endurox_AtmiCtx_tpresume", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tpresume},
    {"ndrxj_Java_org_endurox_AtmiCtx_tpgetlev", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_tpgetlev},
    {"ndrxj_Java_org_endurox_AtmiCtx_installTermSigHandler", (void *)&p_ndrxj_Java_org_endurox_AtmiCtx_installTermSigHandler},
    {"ndrxj_Java_org_endurox_BExprTree_Btreefree", (void *)&p_ndrxj_Java_org_endurox_BExprTree_Btreefree},
    {"ndrxj_Java_org_endurox_TypedBuffer_tpfree", (void *)&p_ndrxj_Java_org_endurox_TypedBuffer_tpfree},
    {"ndrxj_Java_org_endurox_TypedBuffer_tprealloc", (void *)&p_ndrxj_Java_org_endurox_TypedBuffer_tprealloc},
    {"ndrxj_Java_org_endurox_TypedBuffer_tptypes", (void *)&p_ndrxj_Java_org_endurox_TypedBuffer_tptypes},
    {"ndrxj_Java_org_endurox_TypedCarray_setBytes", (void *)&p_ndrxj_Java_org_endurox_TypedCarray_setBytes},
    {"ndrxj_Java_org_endurox_TypedCarray_getBytes", (void *)&p_ndrxj_Java_org_endurox_TypedCarray_getBytes},
    {"ndrxj_Java_org_endurox_TypedJson_setJSON", (void *)&p_ndrxj_Java_org_endurox_TypedJson_setJSON},
    {"ndrxj_Java_org_endurox_TypedJson_getJSON", (void *)&p_ndrxj_Java_org_endurox_TypedJson_getJSON},
    {"ndrxj_Java_org_endurox_TypedString_setString", (void *)&p_ndrxj_Java_org_endurox_TypedString_setString},
    {"ndrxj_Java_org_endurox_TypedString_getString", (void *)&p_ndrxj_Java_org_endurox_TypedString_getString},
    {"ndrxj_Java_org_endurox_TypedUbf_Badd__IS", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Badd__IS},
    {"ndrxj_Java_org_endurox_TypedUbf_Badd__IJ", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Badd__IJ},
    {"ndrxj_Java_org_endurox_TypedUbf_Badd__IB", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Badd__IB},
    {"ndrxj_Java_org_endurox_TypedUbf_Badd__IF", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Badd__IF},
    {"ndrxj_Java_org_endurox_TypedUbf_Badd__ID", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Badd__ID},
    {"ndrxj_Java_org_endurox_TypedUbf_Badd__ILjava_lang_String_2", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Badd__ILjava_lang_String_2},
    {"ndrxj_Java_org_endurox_TypedUbf_Badd__I_3B", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Badd__I_3B},
    {"ndrxj_Java_org_endurox_TypedUbf_Bprint", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Bprint},
    {"ndrxj_Java_org_endurox_TypedUbf_BgetShort", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_BgetShort},
    {"ndrxj_Java_org_endurox_TypedUbf_BgetLong", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_BgetLong},
    {"ndrxj_Java_org_endurox_TypedUbf_BgetByte", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_BgetByte},
    {"ndrxj_Java_org_endurox_TypedUbf_BgetFloat", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_BgetFloat},
    {"ndrxj_Java_org_endurox_TypedUbf_BgetDouble", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_BgetDouble},
    {"ndrxj_Java_org_endurox_TypedUbf_BgetString", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_BgetString},
    {"ndrxj_Java_org_endurox_TypedUbf_BgetByteArr", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_BgetByteArr},
    {"ndrxj_Java_org_endurox_TypedUbf_Baddfast__ISLorg_endurox_BFldLocInfo_2", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Baddfast__ISLorg_endurox_BFldLocInfo_2},
    {"ndrxj_Java_org_endurox_TypedUbf_Baddfast__IJLorg_endurox_BFldLocInfo_2", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Baddfast__IJLorg_endurox_BFldLocInfo_2},
    {"ndrxj_Java_org_endurox_TypedUbf_Baddfast__IBLorg_endurox_BFldLocInfo_2", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Baddfast__IBLorg_endurox_BFldLocInfo_2},
    {"ndrxj_Java_org_endurox_TypedUbf_Baddfast__IFLorg_endurox_BFldLocInfo_2", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Baddfast__IFLorg_endurox_BFldLocInfo_2},
    {"ndrxj_Java_org_endurox_TypedUbf_Baddfast__IDLorg_endurox_BFldLocInfo_2", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Baddfast__IDLorg_endurox_BFldLocInfo_2},
    {"ndrxj_Java_org_endurox_TypedUbf_Baddfast__ILjava_lang_String_2Lorg_endurox_BFldLocInfo_2", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Baddfast__ILjava_lang_String_2Lorg_endurox_BFldLocInfo_2},
    {"ndrxj_Java_org_endurox_TypedUbf_Baddfast__I_3BLorg_endurox_BFldLocInfo_2", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Baddfast__I_3BLorg_endurox_BFldLocInfo_2},
    {"ndrxj_Java_org_endurox_TypedUbf_Bchg__IIS", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Bchg__IIS},
    {"ndrxj_Java_org_endurox_TypedUbf_Bchg__IIJ", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Bchg__IIJ},
    {"ndrxj_Java_org_endurox_TypedUbf_Bchg__IIB", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Bchg__IIB},
    {"ndrxj_Java_org_endurox_TypedUbf_Bchg__IIF", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Bchg__IIF},
    {"ndrxj_Java_org_endurox_TypedUbf_Bchg__IID", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Bchg__IID},
    {"ndrxj_Java_org_endurox_TypedUbf_Bchg__IILjava_lang_String_2", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Bchg__IILjava_lang_String_2},
    {"ndrxj_Java_org_endurox_TypedUbf_Bchg__II_3B", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Bchg__II_3B},
    {"ndrxj_Java_org_endurox_TypedUbf_Bboolev", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Bboolev},
    {"ndrxj_Java_org_endurox_TypedUbf_Bqboolev", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Bqboolev},
    {"ndrxj_Java_org_endurox_TypedUbf_Bfloatev", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Bfloatev},
    {"ndrxj_Java_org_endurox_TypedUbf_Bdel", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Bdel},
    {"ndrxj_Java_org_endurox_TypedUbf_Bdelall", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Bdelall},
    {"ndrxj_Java_org_endurox_TypedUbf_Bpres", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Bpres},
    {"ndrxj_Java_org_endurox_TypedUbf_Bextread", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Bextread},
    {"ndrxj_Java_org_endurox_TypedUbf_Bisubf", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Bisubf},
    {"ndrxj_Java_org_endurox_TypedUbf_Blen", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Blen},
    {"ndrxj_Java_org_endurox_TypedUbf_Bnext", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Bnext},
    {"ndrxj_Java_org_endurox_TypedUbf_Boccur", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Boccur},
    {"ndrxj_Java_org_endurox_TypedUbf_Bproj", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Bproj},
    {"ndrxj_Java_org_endurox_TypedUbf_Bread", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Bread},
    {"ndrxj_Java_org_endurox_TypedUbf_Bwrite", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Bwrite},
    {"ndrxj_Java_org_endurox_TypedUbf_Bsizeof", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Bsizeof},
    {"ndrxj_Java_org_endurox_TypedUbf_Bunused", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Bunused},
    {"ndrxj_Java_org_endurox_TypedUbf_Bused", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Bused},
    {"ndrxj_Java_org_endurox_TypedUbf_Binit", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Binit},
    {"ndrxj_Java_org_endurox_TypedUbf_Bdelete", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Bdelete},
    {"ndrxj_Java_org_endurox_TypedUbf_Bconcat", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Bconcat},
    {"ndrxj_Java_org_endurox_TypedUbf_Bcpy", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Bcpy},
    {"ndrxj_Java_org_endurox_TypedUbf_Bprojcpy", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Bprojcpy},
    {"ndrxj_Java_org_endurox_TypedUbf_Bupdate", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Bupdate},
    {"ndrxj_Java_org_endurox_TypedUbf_Bcmp", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Bcmp},
    {"ndrxj_Java_org_endurox_TypedUbf_Bsubset", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Bsubset},
    {"ndrxj_Java_org_endurox_TypedUbf_tpjsontoubf", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_tpjsontoubf},
    {"ndrxj_Java_org_endurox_TypedUbf_tpubftojson", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_tpubftojson},
    {"ndrxj_Java_org_endurox_TypedUbf_tplogprintubf", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_tplogprintubf},
    {"ndrxj_Java_org_endurox_TypedUbf_Bnum", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Bnum},
    {"ndrxj_Java_org_endurox_TypedUbf_Bjoin", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Bjoin},
    {"ndrxj_Java_org_endurox_TypedUbf_Bojoin", (void *)&p_ndrxj_Java_org_endurox_TypedUbf_Bojoin},
    {NULL, NULL}
};
    
/**
 * Set to true if library is initialize / ptrs resolved
 */
exprivate int volatile M_lib_init = EXFALSE;
exprivate void * M_handle = NULL;

/**
 * Lock for init
 */
MUTEX_LOCKDECL(M_lib_init_lock);

/*---------------------------Prototypes---------------------------------*/

/**
 * Throw exception
 * @param env java env
 * @param msg message
 */
exprivate void ndrxj_lite_exception(JNIEnv *env, char *msg)
{
    (*env)->ThrowNew(env, (*env)->FindClass(env, "java/lang/Exception"), msg);
}

/**
 * Perform library init with mutex lock to avoid twice init - protect from
 * threaded access
 * @param[in] env Java env
 * @return EXSUCCEED/EXFAIL
 */
exprivate int ndrxj_lib_init(JNIEnv *env)
{
    int ret = EXSUCCEED;
    char buf[512];
#if EX_OS_DARWIN   
    char *lib = "libexjava.dylib";
#else
    char *lib = "libexjava.so";
#endif
    int i;
    
    MUTEX_LOCK_V(M_lib_init_lock);
    
    if (!M_lib_init)
    {
        /* check the symbol, if have one, then load directly
         * if does not have symbol, then load the library
         * Symbol mapping shall be done in separate function.
         */
        
        if (NULL==dlsym( RTLD_DEFAULT, "ndrxj_Java_org_endurox_AtmiCtx_tpnewctxt" ))
        {
            /* load shared library */
            M_handle = dlopen (lib, RTLD_NOW | RTLD_GLOBAL);
            
            if (!M_handle)
            {
                snprintf(buf, sizeof(buf), "Failed to load %s: %s", lib, dlerror());
                ndrxj_lite_exception(env, buf);
                EXFAIL_OUT(ret);
            }
        }
        
        /* load mappings, all maps shall succeed, else we give error */
        for (i=0; NULL!=M_funcmap[i].symbol; i++)
        {
            (*M_funcmap[i].funcptr) = dlsym(M_handle, M_funcmap[i].symbol);
            
            if (NULL==(*M_funcmap[i].funcptr))
            {
                snprintf(buf, sizeof(buf), "Failed to resolve `%s' function", 
                        M_funcmap[i].symbol);
                ndrxj_lite_exception(env, buf);
                EXFAIL_OUT(ret);
            }
        }
    }
    
out:
    MUTEX_UNLOCK_V(M_lib_init_lock);
    
    return ret;
}


/**
 * Load the function mappings.
 * If mappings are OK, warm up the caches
 */
expublic JNICALL jint JNI_OnLoad(JavaVM* vm, void* reserved) {
    JNIEnv* env;
    
    if ((*vm)->GetEnv(vm, (void **) &env, JNI_VERSION_1_2) != JNI_OK) {
        return JNI_ERR;
    } 
    else 
    {
        if (EXSUCCEED!=ndrxj_lib_init(env))
        {
            return JNI_ERR;
        }
        
        /* Build up the caches */
        if (EXSUCCEED!=ndrxj_caches_load(env))
        {
            return JNI_ERR;
        }
        
    }
    
    return JNI_VERSION_1_2;
}

/**
 * Remove cached data
 */
expublic JNICALL void JNI_OnUnload(JavaVM *vm, void *reserved) {
    JNIEnv* env;
    if ((*vm)->GetEnv(vm, (void **) &env, JNI_VERSION_1_2) != JNI_OK) {
        // Something is wrong but nothing we can do about this :(
        return;
    } else {
        
        /*
         *  Nothing to remove at the moment...
         * Delete the caches
         * */
        ndrxj_caches_unload(env);
    }
}

/**
 * Auto generated
 */
expublic jobject JNICALL Java_org_endurox_AtmiCtx_getAtmiError (JNIEnv * v0,  jobject v1)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jobject)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_AtmiCtx_getAtmiError(v0, v1);
}

/**
 * Auto generated
 */
expublic jlong JNICALL Java_org_endurox_AtmiCtx_tpnewctxt (JNIEnv * v0,  jclass v1)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jlong)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_AtmiCtx_tpnewctxt(v0, v1);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_AtmiCtx_tpfreectxt (JNIEnv * v0,  jclass v1,  jlong v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_AtmiCtx_tpfreectxt(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic jobject JNICALL Java_org_endurox_AtmiCtx_tpalloc (JNIEnv * v0,  jobject v1,  jstring v2,  jstring v3,  jlong v4)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jobject)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_AtmiCtx_tpalloc(v0, v1, v2, v3, v4);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_AtmiCtx_tpterm (JNIEnv * v0,  jobject v1)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_AtmiCtx_tpterm(v0, v1);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_AtmiCtx_finalizeC (JNIEnv * v0,  jclass v1,  jlong v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_AtmiCtx_finalizeC(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_AtmiCtx_tpreturn (JNIEnv * v0,  jobject v1,  jint v2,  jlong v3,  jobject v4,  jlong v5)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_AtmiCtx_tpreturn(v0, v1, v2, v3, v4, v5);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_AtmiCtx_tpforward (JNIEnv * v0,  jobject v1,  jstring v2,  jobject v3,  jlong v4)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_AtmiCtx_tpforward(v0, v1, v2, v3, v4);
}

/**
 * Auto generated
 */
expublic jint JNICALL Java_org_endurox_AtmiCtx_tpRunC (JNIEnv * v0,  jobject v1,  jobjectArray v2,  jboolean v3)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jint)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_AtmiCtx_tpRunC(v0, v1, v2, v3);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_AtmiCtx_tplogC (JNIEnv * v0,  jobject v1,  jint v2,  jstring v3,  jlong v4,  jstring v5)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_AtmiCtx_tplogC(v0, v1, v2, v3, v4, v5);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_AtmiCtx_tplogndrxC (JNIEnv * v0,  jobject v1,  jint v2,  jstring v3,  jlong v4,  jstring v5)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_AtmiCtx_tplogndrxC(v0, v1, v2, v3, v4, v5);
}

/**
 * Auto generated
 */
expublic jint JNICALL Java_org_endurox_AtmiCtx_tplogqinfo (JNIEnv * v0,  jobject v1,  jint v2,  jlong v3)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jint)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_AtmiCtx_tplogqinfo(v0, v1, v2, v3);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_AtmiCtx_tpadvertiseC (JNIEnv * v0,  jobject v1,  jstring v2,  jstring v3)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_AtmiCtx_tpadvertiseC(v0, v1, v2, v3);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_AtmiCtx_tplogubfex (JNIEnv * v0,  jobject v1,  jint v2,  jstring v3,  jthrowable v4)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_AtmiCtx_tplogubfex(v0, v1, v2, v3, v4);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_AtmiCtx_tplogndrxex (JNIEnv * v0,  jobject v1,  jint v2,  jstring v3,  jthrowable v4)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_AtmiCtx_tplogndrxex(v0, v1, v2, v3, v4);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_AtmiCtx_tplogex (JNIEnv * v0,  jobject v1,  jint v2,  jstring v3,  jthrowable v4)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_AtmiCtx_tplogex(v0, v1, v2, v3, v4);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_AtmiCtx_userlogex (JNIEnv * v0,  jobject v1,  jstring v2,  jthrowable v3)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_AtmiCtx_userlogex(v0, v1, v2, v3);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_AtmiCtx_tplogDump (JNIEnv * v0,  jobject v1,  jint v2,  jstring v3,  jbyteArray v4)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_AtmiCtx_tplogDump(v0, v1, v2, v3, v4);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_AtmiCtx_tplogDumpDiff (JNIEnv * v0,  jobject v1,  jint v2,  jstring v3,  jbyteArray v4,  jbyteArray v5)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_AtmiCtx_tplogDumpDiff(v0, v1, v2, v3, v4, v5);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_AtmiCtx_tpinit (JNIEnv * v0,  jobject v1,  jobject v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_AtmiCtx_tpinit(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_AtmiCtx_userlogC (JNIEnv * v0,  jobject v1,  jstring v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_AtmiCtx_userlogC(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic jobject JNICALL Java_org_endurox_AtmiCtx_tpcall (JNIEnv * v0,  jobject v1,  jstring v2,  jobject v3,  jlong v4)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jobject)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_AtmiCtx_tpcall(v0, v1, v2, v3, v4);
}

/**
 * Auto generated
 */
expublic jint JNICALL Java_org_endurox_AtmiCtx_tpacall (JNIEnv * v0,  jobject v1,  jstring v2,  jobject v3,  jlong v4)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jint)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_AtmiCtx_tpacall(v0, v1, v2, v3, v4);
}

/**
 * Auto generated
 */
expublic jobject JNICALL Java_org_endurox_AtmiCtx_tpgetrply (JNIEnv * v0,  jobject v1,  jint v2,  jobject v3,  jlong v4)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jobject)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_AtmiCtx_tpgetrply(v0, v1, v2, v3, v4);
}

/**
 * Auto generated
 */
expublic jint JNICALL Java_org_endurox_AtmiCtx_tpconnect (JNIEnv * v0,  jobject v1,  jstring v2,  jobject v3,  jlong v4)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jint)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_AtmiCtx_tpconnect(v0, v1, v2, v3, v4);
}

/**
 * Auto generated
 */
expublic jlong JNICALL Java_org_endurox_AtmiCtx_tpsend (JNIEnv * v0,  jobject v1,  jint v2,  jobject v3,  jlong v4)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jlong)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_AtmiCtx_tpsend(v0, v1, v2, v3, v4);
}

/**
 * Auto generated
 */
expublic jobject JNICALL Java_org_endurox_AtmiCtx_tprecv (JNIEnv * v0,  jobject v1,  jint v2,  jobject v3,  jlong v4)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jobject)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_AtmiCtx_tprecv(v0, v1, v2, v3, v4);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_AtmiCtx_tpdiscon (JNIEnv * v0,  jobject v1,  jint v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_AtmiCtx_tpdiscon(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_AtmiCtx_tpcancel (JNIEnv * v0,  jobject v1,  jint v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_AtmiCtx_tpcancel(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic jobject JNICALL Java_org_endurox_AtmiCtx_Bboolco (JNIEnv * v0,  jobject v1,  jstring v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jobject)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_AtmiCtx_Bboolco(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_AtmiCtx_Bboolpr (JNIEnv * v0,  jobject v1,  jobject v2,  jobject v3)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_AtmiCtx_Bboolpr(v0, v1, v2, v3);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_AtmiCtx_BboolsetcbfC (JNIEnv * v0,  jobject v1,  jstring v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_AtmiCtx_BboolsetcbfC(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic jstring JNICALL Java_org_endurox_AtmiCtx_Btype (JNIEnv * v0,  jobject v1,  jint v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jstring)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_AtmiCtx_Btype(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic jstring JNICALL Java_org_endurox_AtmiCtx_Bfname (JNIEnv * v0,  jobject v1,  jint v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jstring)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_AtmiCtx_Bfname(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic jint JNICALL Java_org_endurox_AtmiCtx_tptoutget (JNIEnv * v0,  jobject v1)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jint)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_AtmiCtx_tptoutget(v0, v1);
}

/**
 * Auto generated
 */
expublic jlong JNICALL Java_org_endurox_AtmiCtx_tpurcode (JNIEnv * v0,  jobject v1)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jlong)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_AtmiCtx_tpurcode(v0, v1);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_AtmiCtx_tptoutset (JNIEnv * v0,  jobject v1,  jint v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_AtmiCtx_tptoutset(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic jlongArray JNICALL Java_org_endurox_AtmiCtx_getBuffers (JNIEnv * v0,  jobject v1)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jlongArray)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_AtmiCtx_getBuffers(v0, v1);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_AtmiCtx_tpsetunsolC (JNIEnv * v0,  jobject v1,  jobject v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_AtmiCtx_tpsetunsolC(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_AtmiCtx_tpnotify (JNIEnv * v0,  jobject v1,  jobject v2,  jobject v3,  jlong v4)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_AtmiCtx_tpnotify(v0, v1, v2, v3, v4);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_AtmiCtx_tpbroadcast (JNIEnv * v0,  jobject v1,  jstring v2,  jstring v3,  jstring v4,  jobject v5,  jlong v6)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_AtmiCtx_tpbroadcast(v0, v1, v2, v3, v4, v5, v6);
}

/**
 * Auto generated
 */
expublic jint JNICALL Java_org_endurox_AtmiCtx_tpchkunsol (JNIEnv * v0,  jobject v1)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jint)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_AtmiCtx_tpchkunsol(v0, v1);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_AtmiCtx_tpenqueue (JNIEnv * v0,  jobject v1,  jstring v2,  jstring v3,  jobject v4,  jobject v5,  jlong v6)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_AtmiCtx_tpenqueue(v0, v1, v2, v3, v4, v5, v6);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_AtmiCtx_tpenqueueex (JNIEnv * v0,  jobject v1,  jshort v2,  jshort v3,  jstring v4,  jobject v5,  jobject v6,  jlong v7)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_AtmiCtx_tpenqueueex(v0, v1, v2, v3, v4, v5, v6, v7);
}

/**
 * Auto generated
 */
expublic jobject JNICALL Java_org_endurox_AtmiCtx_tpdequeue (JNIEnv * v0,  jobject v1,  jstring v2,  jstring v3,  jobject v4,  jobject v5,  jlong v6)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jobject)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_AtmiCtx_tpdequeue(v0, v1, v2, v3, v4, v5, v6);
}

/**
 * Auto generated
 */
expublic jobject JNICALL Java_org_endurox_AtmiCtx_tpdequeueex (JNIEnv * v0,  jobject v1,  jshort v2,  jshort v3,  jstring v4,  jobject v5,  jobject v6,  jlong v7)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jobject)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_AtmiCtx_tpdequeueex(v0, v1, v2, v3, v4, v5, v6, v7);
}

/**
 * Auto generated
 */
expublic jlong JNICALL Java_org_endurox_AtmiCtx_tpsrvgetctxdata (JNIEnv * v0,  jobject v1)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jlong)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_AtmiCtx_tpsrvgetctxdata(v0, v1);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_AtmiCtx_tpsrvsetctxdata (JNIEnv * v0,  jobject v1,  jlong v2,  jlong v3)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_AtmiCtx_tpsrvsetctxdata(v0, v1, v2, v3);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_AtmiCtx_tpsrvfreectxdata (JNIEnv * v0,  jobject v1,  jlong v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_AtmiCtx_tpsrvfreectxdata(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_AtmiCtx_tpcontinue (JNIEnv * v0,  jobject v1)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_AtmiCtx_tpcontinue(v0, v1);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_AtmiCtx_tpopen (JNIEnv * v0,  jobject v1)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_AtmiCtx_tpopen(v0, v1);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_AtmiCtx_tpclose (JNIEnv * v0,  jobject v1)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_AtmiCtx_tpclose(v0, v1);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_AtmiCtx_tpbegin (JNIEnv * v0,  jobject v1,  jlong v2,  jlong v3)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_AtmiCtx_tpbegin(v0, v1, v2, v3);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_AtmiCtx_tpcommit (JNIEnv * v0,  jobject v1,  jlong v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_AtmiCtx_tpcommit(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_AtmiCtx_tpabort (JNIEnv * v0,  jobject v1,  jlong v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_AtmiCtx_tpabort(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic jobject JNICALL Java_org_endurox_AtmiCtx_tpsuspend (JNIEnv * v0,  jobject v1,  jlong v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jobject)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_AtmiCtx_tpsuspend(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_AtmiCtx_tpresume (JNIEnv * v0,  jobject v1,  jobject v2,  jlong v3)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_AtmiCtx_tpresume(v0, v1, v2, v3);
}

/**
 * Auto generated
 */
expublic jint JNICALL Java_org_endurox_AtmiCtx_tpgetlev (JNIEnv * v0,  jobject v1)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jint)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_AtmiCtx_tpgetlev(v0, v1);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_AtmiCtx_installTermSigHandler (JNIEnv * v0,  jobject v1,  jobject v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_AtmiCtx_installTermSigHandler(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_BExprTree_Btreefree (JNIEnv * v0,  jobject v1,  jlong v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_BExprTree_Btreefree(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedBuffer_tpfree (JNIEnv * v0,  jobject v1,  jlong v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedBuffer_tpfree(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedBuffer_tprealloc (JNIEnv * v0,  jobject v1,  jlong v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedBuffer_tprealloc(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic jobject JNICALL Java_org_endurox_TypedBuffer_tptypes (JNIEnv * v0,  jobject v1)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jobject)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_TypedBuffer_tptypes(v0, v1);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedCarray_setBytes (JNIEnv * v0,  jobject v1,  jbyteArray v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedCarray_setBytes(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic jbyteArray JNICALL Java_org_endurox_TypedCarray_getBytes (JNIEnv * v0,  jobject v1)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jbyteArray)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_TypedCarray_getBytes(v0, v1);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedJson_setJSON (JNIEnv * v0,  jobject v1,  jstring v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedJson_setJSON(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic jstring JNICALL Java_org_endurox_TypedJson_getJSON (JNIEnv * v0,  jobject v1)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jstring)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_TypedJson_getJSON(v0, v1);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedString_setString (JNIEnv * v0,  jobject v1,  jstring v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedString_setString(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic jstring JNICALL Java_org_endurox_TypedString_getString (JNIEnv * v0,  jobject v1)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jstring)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_TypedString_getString(v0, v1);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedUbf_Badd__IS (JNIEnv * v0,  jobject v1,  jint v2,  jshort v3)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedUbf_Badd__IS(v0, v1, v2, v3);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedUbf_Badd__IJ (JNIEnv * v0,  jobject v1,  jint v2,  jlong v3)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedUbf_Badd__IJ(v0, v1, v2, v3);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedUbf_Badd__IB (JNIEnv * v0,  jobject v1,  jint v2,  jbyte v3)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedUbf_Badd__IB(v0, v1, v2, v3);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedUbf_Badd__IF (JNIEnv * v0,  jobject v1,  jint v2,  jfloat v3)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedUbf_Badd__IF(v0, v1, v2, v3);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedUbf_Badd__ID (JNIEnv * v0,  jobject v1,  jint v2,  jdouble v3)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedUbf_Badd__ID(v0, v1, v2, v3);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedUbf_Badd__ILjava_lang_String_2 (JNIEnv * v0,  jobject v1,  jint v2,  jstring v3)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedUbf_Badd__ILjava_lang_String_2(v0, v1, v2, v3);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedUbf_Badd__I_3B (JNIEnv * v0,  jobject v1,  jint v2,  jbyteArray v3)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedUbf_Badd__I_3B(v0, v1, v2, v3);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedUbf_Bprint (JNIEnv * v0,  jobject v1)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedUbf_Bprint(v0, v1);
}

/**
 * Auto generated
 */
expublic jshort JNICALL Java_org_endurox_TypedUbf_BgetShort (JNIEnv * v0,  jobject v1,  jint v2,  jint v3)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jshort)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_TypedUbf_BgetShort(v0, v1, v2, v3);
}

/**
 * Auto generated
 */
expublic jlong JNICALL Java_org_endurox_TypedUbf_BgetLong (JNIEnv * v0,  jobject v1,  jint v2,  jint v3)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jlong)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_TypedUbf_BgetLong(v0, v1, v2, v3);
}

/**
 * Auto generated
 */
expublic jbyte JNICALL Java_org_endurox_TypedUbf_BgetByte (JNIEnv * v0,  jobject v1,  jint v2,  jint v3)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jbyte)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_TypedUbf_BgetByte(v0, v1, v2, v3);
}

/**
 * Auto generated
 */
expublic jfloat JNICALL Java_org_endurox_TypedUbf_BgetFloat (JNIEnv * v0,  jobject v1,  jint v2,  jint v3)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jfloat)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_TypedUbf_BgetFloat(v0, v1, v2, v3);
}

/**
 * Auto generated
 */
expublic jdouble JNICALL Java_org_endurox_TypedUbf_BgetDouble (JNIEnv * v0,  jobject v1,  jint v2,  jint v3)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jdouble)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_TypedUbf_BgetDouble(v0, v1, v2, v3);
}

/**
 * Auto generated
 */
expublic jstring JNICALL Java_org_endurox_TypedUbf_BgetString (JNIEnv * v0,  jobject v1,  jint v2,  jint v3)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jstring)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_TypedUbf_BgetString(v0, v1, v2, v3);
}

/**
 * Auto generated
 */
expublic jbyteArray JNICALL Java_org_endurox_TypedUbf_BgetByteArr (JNIEnv * v0,  jobject v1,  jint v2,  jint v3)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jbyteArray)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_TypedUbf_BgetByteArr(v0, v1, v2, v3);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedUbf_Baddfast__ISLorg_endurox_BFldLocInfo_2 (JNIEnv * v0,  jobject v1,  jint v2,  jshort v3,  jobject v4)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedUbf_Baddfast__ISLorg_endurox_BFldLocInfo_2(v0, v1, v2, v3, v4);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedUbf_Baddfast__IJLorg_endurox_BFldLocInfo_2 (JNIEnv * v0,  jobject v1,  jint v2,  jlong v3,  jobject v4)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedUbf_Baddfast__IJLorg_endurox_BFldLocInfo_2(v0, v1, v2, v3, v4);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedUbf_Baddfast__IBLorg_endurox_BFldLocInfo_2 (JNIEnv * v0,  jobject v1,  jint v2,  jbyte v3,  jobject v4)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedUbf_Baddfast__IBLorg_endurox_BFldLocInfo_2(v0, v1, v2, v3, v4);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedUbf_Baddfast__IFLorg_endurox_BFldLocInfo_2 (JNIEnv * v0,  jobject v1,  jint v2,  jfloat v3,  jobject v4)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedUbf_Baddfast__IFLorg_endurox_BFldLocInfo_2(v0, v1, v2, v3, v4);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedUbf_Baddfast__IDLorg_endurox_BFldLocInfo_2 (JNIEnv * v0,  jobject v1,  jint v2,  jdouble v3,  jobject v4)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedUbf_Baddfast__IDLorg_endurox_BFldLocInfo_2(v0, v1, v2, v3, v4);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedUbf_Baddfast__ILjava_lang_String_2Lorg_endurox_BFldLocInfo_2 (JNIEnv * v0,  jobject v1,  jint v2,  jstring v3,  jobject v4)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedUbf_Baddfast__ILjava_lang_String_2Lorg_endurox_BFldLocInfo_2(v0, v1, v2, v3, v4);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedUbf_Baddfast__I_3BLorg_endurox_BFldLocInfo_2 (JNIEnv * v0,  jobject v1,  jint v2,  jbyteArray v3,  jobject v4)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedUbf_Baddfast__I_3BLorg_endurox_BFldLocInfo_2(v0, v1, v2, v3, v4);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedUbf_Bchg__IIS (JNIEnv * v0,  jobject v1,  jint v2,  jint v3,  jshort v4)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedUbf_Bchg__IIS(v0, v1, v2, v3, v4);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedUbf_Bchg__IIJ (JNIEnv * v0,  jobject v1,  jint v2,  jint v3,  jlong v4)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedUbf_Bchg__IIJ(v0, v1, v2, v3, v4);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedUbf_Bchg__IIB (JNIEnv * v0,  jobject v1,  jint v2,  jint v3,  jbyte v4)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedUbf_Bchg__IIB(v0, v1, v2, v3, v4);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedUbf_Bchg__IIF (JNIEnv * v0,  jobject v1,  jint v2,  jint v3,  jfloat v4)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedUbf_Bchg__IIF(v0, v1, v2, v3, v4);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedUbf_Bchg__IID (JNIEnv * v0,  jobject v1,  jint v2,  jint v3,  jdouble v4)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedUbf_Bchg__IID(v0, v1, v2, v3, v4);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedUbf_Bchg__IILjava_lang_String_2 (JNIEnv * v0,  jobject v1,  jint v2,  jint v3,  jstring v4)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedUbf_Bchg__IILjava_lang_String_2(v0, v1, v2, v3, v4);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedUbf_Bchg__II_3B (JNIEnv * v0,  jobject v1,  jint v2,  jint v3,  jbyteArray v4)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedUbf_Bchg__II_3B(v0, v1, v2, v3, v4);
}

/**
 * Auto generated
 */
expublic jboolean JNICALL Java_org_endurox_TypedUbf_Bboolev (JNIEnv * v0,  jobject v1,  jobject v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jboolean)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_TypedUbf_Bboolev(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic jboolean JNICALL Java_org_endurox_TypedUbf_Bqboolev (JNIEnv * v0,  jobject v1,  jstring v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jboolean)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_TypedUbf_Bqboolev(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic jdouble JNICALL Java_org_endurox_TypedUbf_Bfloatev (JNIEnv * v0,  jobject v1,  jobject v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jdouble)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_TypedUbf_Bfloatev(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedUbf_Bdel (JNIEnv * v0,  jobject v1,  jint v2,  jint v3)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedUbf_Bdel(v0, v1, v2, v3);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedUbf_Bdelall (JNIEnv * v0,  jobject v1,  jint v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedUbf_Bdelall(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic jboolean JNICALL Java_org_endurox_TypedUbf_Bpres (JNIEnv * v0,  jobject v1,  jint v2,  jint v3)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jboolean)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_TypedUbf_Bpres(v0, v1, v2, v3);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedUbf_Bextread (JNIEnv * v0,  jobject v1,  jobject v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedUbf_Bextread(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic jboolean JNICALL Java_org_endurox_TypedUbf_Bisubf (JNIEnv * v0,  jobject v1)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jboolean)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_TypedUbf_Bisubf(v0, v1);
}

/**
 * Auto generated
 */
expublic jint JNICALL Java_org_endurox_TypedUbf_Blen (JNIEnv * v0,  jobject v1,  jint v2,  jint v3)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jint)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_TypedUbf_Blen(v0, v1, v2, v3);
}

/**
 * Auto generated
 */
expublic jobject JNICALL Java_org_endurox_TypedUbf_Bnext (JNIEnv * v0,  jobject v1,  jboolean v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jobject)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_TypedUbf_Bnext(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic jint JNICALL Java_org_endurox_TypedUbf_Boccur (JNIEnv * v0,  jobject v1,  jint v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jint)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_TypedUbf_Boccur(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedUbf_Bproj (JNIEnv * v0,  jobject v1,  jintArray v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedUbf_Bproj(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedUbf_Bread (JNIEnv * v0,  jobject v1,  jbyteArray v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedUbf_Bread(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic jbyteArray JNICALL Java_org_endurox_TypedUbf_Bwrite (JNIEnv * v0,  jobject v1)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jbyteArray)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_TypedUbf_Bwrite(v0, v1);
}

/**
 * Auto generated
 */
expublic jlong JNICALL Java_org_endurox_TypedUbf_Bsizeof (JNIEnv * v0,  jobject v1)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jlong)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_TypedUbf_Bsizeof(v0, v1);
}

/**
 * Auto generated
 */
expublic jlong JNICALL Java_org_endurox_TypedUbf_Bunused (JNIEnv * v0,  jobject v1)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jlong)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_TypedUbf_Bunused(v0, v1);
}

/**
 * Auto generated
 */
expublic jlong JNICALL Java_org_endurox_TypedUbf_Bused (JNIEnv * v0,  jobject v1)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jlong)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_TypedUbf_Bused(v0, v1);
}

/**
 * Auto generated
 */
expublic jlong JNICALL Java_org_endurox_TypedUbf_Binit (JNIEnv * v0,  jobject v1)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jlong)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_TypedUbf_Binit(v0, v1);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedUbf_Bdelete (JNIEnv * v0,  jobject v1,  jintArray v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedUbf_Bdelete(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedUbf_Bconcat (JNIEnv * v0,  jobject v1,  jobject v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedUbf_Bconcat(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedUbf_Bcpy (JNIEnv * v0,  jobject v1,  jobject v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedUbf_Bcpy(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedUbf_Bprojcpy (JNIEnv * v0,  jobject v1,  jobject v2,  jintArray v3)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedUbf_Bprojcpy(v0, v1, v2, v3);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedUbf_Bupdate (JNIEnv * v0,  jobject v1,  jobject v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedUbf_Bupdate(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic jint JNICALL Java_org_endurox_TypedUbf_Bcmp (JNIEnv * v0,  jobject v1,  jobject v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jint)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_TypedUbf_Bcmp(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic jboolean JNICALL Java_org_endurox_TypedUbf_Bsubset (JNIEnv * v0,  jobject v1,  jobject v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jboolean)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_TypedUbf_Bsubset(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedUbf_tpjsontoubf (JNIEnv * v0,  jobject v1,  jstring v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedUbf_tpjsontoubf(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic jstring JNICALL Java_org_endurox_TypedUbf_tpubftojson (JNIEnv * v0,  jobject v1)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jstring)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_TypedUbf_tpubftojson(v0, v1);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedUbf_tplogprintubf (JNIEnv * v0,  jobject v1,  jint v2,  jstring v3)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedUbf_tplogprintubf(v0, v1, v2, v3);
}

/**
 * Auto generated
 */
expublic jint JNICALL Java_org_endurox_TypedUbf_Bnum (JNIEnv * v0,  jobject v1)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return (jint)0;
        }
    }
    
    return p_ndrxj_Java_org_endurox_TypedUbf_Bnum(v0, v1);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedUbf_Bjoin (JNIEnv * v0,  jobject v1,  jobject v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedUbf_Bjoin(v0, v1, v2);
}

/**
 * Auto generated
 */
expublic void JNICALL Java_org_endurox_TypedUbf_Bojoin (JNIEnv * v0,  jobject v1,  jobject v2)
{
    if (!M_lib_init)
    {
        if (EXSUCCEED!=ndrxj_lib_init(v0))
        {
            return;
        }
    }
    
    p_ndrxj_Java_org_endurox_TypedUbf_Bojoin(v0, v1, v2);
}

#undef __USE_GNU
/* vim: set ts=4 sw=4 et smartindent: */
